[path]
log_path = "C:/Users/eserkai/OneDrive - Ericsson/Documents/Programming/Python/Training/user-management-app/logs"
csv_path = "C:/Users/eserkai/OneDrive - Ericsson/Documents/Programming/Python/Training/user-management-app/files/users.csv"
